version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: yarn install --ignore-scripts

      - run:
          name: Run Tests
          command: yarn ci
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
